### ISSUE TITLE
Preview Issues

### ISSUE THREAD

**Issue by MadDog443** [hypherionmc/simple-rpc-editor#3]
![image](https://user-images.githubusercontent.com/52639083/135707342-f9ca0155-7f45-4cf5-8854-06ca7fb04be4.png)
![image](https://user-images.githubusercontent.com/52639083/135707359-f9e2a2b0-15f7-4a19-8287-21540b8484d6.png)
Currently I am unable to have the secondary icon change based on %launcher% value, not sure if this is due to Discord Developer Portal being slow to update Art Assets or it's case sensitive. Also the name is not showing up as "MadPack" in the preview like it should.

**Comment by MadDog443** [comment]
ah, it seems to be case sensitive to capitalization, this is a big issue considering Discord does not allow capitalization on icon names.

**Comment by hypherionmc** [comment]
I'm not sure what you mean by case sensitive? Nothing about the editor or the mod is case sensitive. It's probably discord caching

As for the pack name, it doesn't show on the editor due to discord api limitations. Only way around it, is to have you login to the app with discord, which is something I'd like to avoid

**Comment by MadDog443** [comment]
> I'm not sure what you mean by case sensitive? Nothing about the editor or the mod is case sensitive. It's probably discord caching

What I meant is that Discord is case sensitive, when you put text in the image selector it allows you to input capitalized characters which breaks it on Discord's end, so anything that is put in there (like %launcher% which does output capitals) should be forced to lowercase.
